site_name: StudyRx
theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  apple-touch-icon-precomposed: images/mobile_icon.png
  include_search_page: false
  search_index_only: true
nav:
  - 前言: index.md
  - 个人页: ./个人页/个人页中心页.md
  - 规范文件:
    - 模板:
      - 课程模板: ./规范文件/模板/课程模板.md
    - 分支规范: ./规范文件/分支规范.md
    - commit 规范: ./规范文件/针对这个文档的额外Angular规范.md
plugins:
  - tags
  - meta
  - privacy
